name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Encrypt Message
      id: encrypt
      run: |
        # Place your Python script for message encryption here
        # For example, you can use the Crypto library as shown in the previous code
        # Replace the following lines with your encryption logic
        python -c 'print("This is a secret message")' > encrypted.txt
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Decrypt Message
      if: success()
      run: |
        # Place your Python script for message decryption here
        # For example, you can use the Crypto library as shown in the previous code
        # Replace the following lines with your decryption logic
        python -c 'print("Decrypted:", open("encrypted.txt").read())'
